service:
  name: ${opt:appName, 'football-alerts'}
  publish: false

provider:
  name: aws
  runtime: nodejs10.x
  region: ${opt:region, 'eu-west-1'}
  stage: ${opt:stage, 'local'}
  environment:
    STAGE: ${self:provider.stage}
    NODE_ENV: ${env:NODE_ENV, 'production'}

package:
  individually: true

plugins:
#  - serverless-step-functions
  - serverless-pseudo-parameters
  - serverless-appsync-plugin
  - serverless-webpack
  - '@football-alerts/serverless-aws-exports'

custom:
  prefix: ${self:service}-${self:provider.stage}

  appSync:
    -
      name: ${self:custom.prefix}-private
      authenticationType: AMAZON_COGNITO_USER_POOLS
      userPoolConfig:
        awsRegion: ${self:provider.region}
        defaultAction: ALLOW
        userPoolId: !Ref CognitoUserPool
      mappingTemplates:
        # Clubs
        -
          dataSource: Clubs
          type: Mutation
          field: createClub
          request: clubs/Mutation.createClub.req.vtl
          response: clubs/Mutation.createClub.res.vtl
        -
          dataSource: Clubs
          type: Mutation
          field: deleteClub
          request: clubs/Mutation.deleteClub.req.vtl
          response: clubs/Mutation.deleteClub.res.vtl
        -
          dataSource: Clubs
          type: Mutation
          field: updateClub
          request: clubs/Mutation.updateClub.req.vtl
          response: clubs/Mutation.updateClub.res.vtl
        -
          dataSource: Clubs
          type: Query
          field: getClub
          request: clubs/Query.getClub.req.vtl
          response: clubs/Query.getClub.res.vtl
        -
          dataSource: Clubs
          type: Query
          field: getClubs
          request: clubs/Query.getClubs.req.vtl
          response: clubs/Query.getClubs.res.vtl

        # Sources
        -
          dataSource: Sources
          type: Mutation
          field: createSource
          request: sources/Mutation.createSource.req.vtl
          response: sources/Mutation.createSource.res.vtl
        -
          dataSource: Sources
          type: Query
          field: getSources
          request: sources/Query.getSources.req.vtl
          response: sources/Query.getSources.res.vtl
      dataSources:
        -
          type: AMAZON_DYNAMODB
          name: Clubs
          description: Clubs table
          config:
            tableName: !Ref ClubsTable
            serviceRoleArn: !GetAtt AppSyncDynamoDbServiceRole.Arn
        -
          type: AMAZON_DYNAMODB
          name: Sources
          description: Sources table
          config:
            tableName: !Ref SourcesTable
            serviceRoleArn: !GetAtt AppSyncDynamoDbServiceRole.Arn

  cognito-transformations:
    develop: Develop
    production: Production

  output:
    files:
      - ../admin/src/aws-exports.js
    graphQlApiUrlName: FootballalertsdevelopprivateGraphQlApiUrl

  webpack:
    includeModules: true

functions:
  UsersRegister:
    handler: src/users/register.handler
    role: UsersRegisterRole
    environment:
      TABLE_NAME: !Ref UsersTable

resources:
  Resources:
    # Cognito
    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.prefix}-user-pool
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: true
        Schema:
          -
            Name: given_name
            AttributeDataType: String
            Mutable: true
            Required: true
          -
            Name: family_name
            AttributeDataType: String
            Mutable: true
            Required: true
          -
            Name: twitter_handle
            AttributeDataType: String
            Mutable: true
            Required: false
          -
            Name: website
            AttributeDataType: String
            Mutable: true
            Required: false
        UsernameAttributes:
          - email
        LambdaConfig:
          PostAuthentication: !GetAtt UsersRegisterLambdaFunction.Arn
          PostConfirmation: !GetAtt UsersRegisterLambdaFunction.Arn

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.prefix}-user-pool-client
        UserPoolId: !Ref CognitoUserPool

    CognitoIdentityPool:
      Type: AWS::Cognito::IdentityPool
      Properties:
        IdentityPoolName: FootballAlerts${self:custom.cognito-transformations.${self:provider.stage}}IdentityPool
        AllowUnauthenticatedIdentities: false
        CognitoIdentityProviders:
          -
            ClientId: !Ref CognitoUserPoolClient
            ProviderName: !GetAtt CognitoUserPool.ProviderName

    CognitoIdentityPoolRoles:
      Type: AWS::Cognito::IdentityPoolRoleAttachment
      Properties:
        IdentityPoolId: !Ref CognitoIdentityPool
        Roles:
          authenticated: !GetAtt CognitoAuthRole.Arn
          unauthenticated: !GetAtt CognitoUnauthRole.Arn

    CognitoAuthRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.prefix}-cognito-auth-role
        Path: /
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Effect: Allow
              Principal:
                Federated: cognito-identity.amazonaws.com
              Action:
                - sts:AssumeRoleWithWebIdentity
              Condition:
                StringEquals:
                  "cognito-identity.amazonaws.com:aud": !Ref CognitoIdentityPool
                "ForAnyValue:StringLike":
                  "cognito-identity.amazonaws.com:amr": authenticated
        Policies:
          -
            PolicyName: ${self:custom.prefix}-cognito-auth-role-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                -
                  Effect: Allow
                  Action:
                    - mobileanalytics:PutEvents
                    - cognito-sync:*
                    - cognito-identity:*
                  Resource: '*'
                -
                  Effect: Allow
                  Action:
                    - execute-api:Invoke
                  Resource: '*'

    CognitoUnauthRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.prefix}-cognito-unauth-role
        Path: /
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Effect: Allow
              Principal:
                Federated: cognito-identity.amazonaws.com
              Action:
                - sts:AssumeRoleWithWebIdentity
              Condition:
                StringEquals:
                  "cognito-identity.amazonaws.com:aud": !Ref CognitoIdentityPool
                "ForAnyValue:StringLike":
                  "cognito-identity.amazonaws.com:amr": unauthenticated
        Policies:
          -
            PolicyName: ${self:custom.prefix}-cognito-unauth-role-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                -
                  Effect: Allow
                  Action:
                    - mobileanalytics:PutEvents
                    - cognito-sync:*
                    - cognito-identity:*
                  Resource: '*'

    # DynamoDB
    ClubsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.prefix}-clubs
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    SourcesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.prefix}-sources
        AttributeDefinitions:
          -
            AttributeName: clubId
            AttributeType: S
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
          -
            AttributeName: clubId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.prefix}-users
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    # IAM
    AppSyncDynamoDbServiceRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.prefix}-appsync-dynamodb-service-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Effect: Allow
              Principal:
                Service:
                  - appsync.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          -
            PolicyName: ${self:custom.prefix}-appsync-dynamodb-service-role-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                -
                  Effect: Allow
                  Action:
                    - dynamodb:DeleteItem
                    - dynamodb:GetItem
                    - dynamodb:PutItem
                    - dynamodb:Query
                    - dynamodb:Scan
                    - dynamodb:UpdateItem
                  Resource:
                    - !GetAtt ClubsTable.Arn
                    - !GetAtt SourcesTable.Arn

    UsersRegisterLambdaFunctionInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        Principal: cognito-idp.amazonaws.com
        FunctionName: !GetAtt UsersRegisterLambdaFunction.Arn
        SourceArn: !GetAtt CognitoUserPool.Arn
        Action: lambda:InvokeFunction

    UsersRegisterRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:custom.prefix}-users-register-role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            -
              Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - sts:AssumeRole
        Policies:
          -
            PolicyName: ${self:custom.prefix}-users-register-role-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                -
                  Effect: Allow
                  Action:
                    - dynamodb:UpdateItem
                  Resource:
                    - !GetAtt UsersTable.Arn

  Outputs:
    IdentityPoolId:
      Value: !Ref CognitoIdentityPool
    Region:
      Value: ${self:provider.region}
    UserPoolClientId:
      Value: !Ref CognitoUserPoolClient
    UserPoolId:
      Value: !Ref CognitoUserPool
